openapi: 3.0.0
info:
  title: My API
  version: "1.0"
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
  /getallusers:
    get:
      summary: Return all users in the database
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: 
                example: 
  /getallgroups:
    get:
      summary: Return all groups in the database
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: 
                example: 
  /getallsales:
    get:
      summary: Return all sales in the database
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: 
                example: 