openapi: 3.0.0
info:
  title: My API
  version: "1.0"
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "Hello World"
  /allusers:
    get:
      summary: Return all users in the database
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: string
                example: "Goodbye World"
